services:
  opendt:
    entrypoint: ["python","-u","/app/src/main.py"]
    environment:
      - OPENDT_DATA_DIR=/app/data
      - OPENDT_SIM_DIR=/app/output/opendt-simulation/raw-output
    volumes:
      - ./:/app
      - ./output/opendt-simulation/raw-output:/app/output/opendt-simulation/raw-output
